### ISSUE TITLE
[Bug]: The description of the lab and the activities of the lab don't seem to match 

### ISSUE THREAD

**Issue by Annie29** [GoogleCloudPlatform/generative-ai#1004]
### File Name

intro_function_calling.ipynb

### What happened?

In the description of the lab (in Why Function Calling), the emphasis is on using functions to reformat output.  None of the examples discussed in the Objectives right below this section seem to have anything to do with reformatting the output.  

In looking at those objectives more closely, there also seem to be some problems. The first objective is to get weather for a location.  This is a fairly classic example of function calling, but it's not covered by the description.  And weather isn't included anywhere else in the lab.

In place of the weather example, there's a section in the lab on "Logging example: Using Function Calling for entity extraction only" that's not included in the objectives.  

These are fairly major problems IMHO.  I also wish the parts of the lab were organized in the same order as the objectives, but I can search a file, so I managed to find where the objectives were, so this feels less important. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by koverholt** [comment]
Thanks for the report!

> In the description of the lab (in Why Function Calling), the emphasis is on using functions to reformat output. None of the examples discussed in the Objectives right below this section seem to have anything to do with reformatting the output.

At its core, Gemini Function Calling is a mode in Gemini to coerce structured output that includes predicted function names and function parameters. Only after the function names and function parameters are returned by Gemini can a user take action using that data, which happens outside of the Gemini SDK/API. In most cases users will take this data and use it to make an API call. The naming of "Function Calling" is confusing in this regard, since the core functionality is all about structured data outputs rather than actually calling functions (confusing, we know).

All of this makes it difficult to explain Function Calling, structured data outputs, JSON responses from the REST API, extracting parameters, then calling the API, as we do in the `Why Function Calling?` section. You can see similar language in the [Gemini Function Calling docs in Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/function-calling). I wish it were easier to explain, and we'll continue to reword, but it's important to explain the structured data responses to clarify that "it doesn't make the function call for you". And "Function Calling" has become a standard term for these type of structured data responses from generative models (e.g., https://python.langchain.com/v0.1/docs/modules/model_io/chat/function_calling/).

> In looking at those objectives more closely, there also seem to be some problems.

Thanks for calling this out! Based on change in behavior and/or issues with different versions of Function Calling over the past few months, I had to rework major sections of this sample notebook, and it seems that the objectives section is now way out of sync with the actual sections. I'll create a PR to address this, and see if I can reword any of the language about structured data outputs and function calls in the intro.
