### ISSUE TITLE
Unable to use matching engine in collab!

### ISSUE THREAD

**Issue by neeraj-mahapatra** [GoogleCloudPlatform/generative-ai#144]
I am not able to use 
Import custom Matching Engine packages
from utils.matching_engine import MatchingEngine
from utils.matching_engine_utils import MatchingEngineUtils

Throwing error as No module named 'utils' after installing utils its giving error as No module named 'utils.matching_engine'.

**Comment by polong-lin** [comment]
Ah yes sorry about that -- it's because you may not have the files from the utills folder, and we didn't add instructions to download it for use in Colab.

Try this:
```
!pip install github-clone

# download the specific folder to a local utils/ folder
!ghclone https://github.com/GoogleCloudPlatform/generative-ai/tree/main/language/examples/document-qa/utils
```

This should download the utils/ folder to your local environment so that you can import the utils methods in Colab.

I'll set up a PR to get this fixed next week.

**Comment by polong-lin** [comment]
Thanks Steve! Should be fixed now in https://github.com/GoogleCloudPlatform/generative-ai/pull/164
