### ISSUE TITLE
Unable to use notebook for grounding with web search - allowlist issue

### ISSUE THREAD

**Issue by cloud-sid** [GoogleCloudPlatform/generative-ai#320]
This is the Nbk : **https://github.com/GoogleCloudPlatform/generative-ai/blob/main/language/grounding/intro-grounding.ipynb**
You guys need to learn how to document the basic prerequisites for code execution. 
The error that shows up is "Project number is not allowlisted for grounding with Web Source." and there's absolutely no documentation to handle this error. Waste of time!!

**Comment by prabha-git** [comment]
Yes , Same issue. ➕

**Comment by koverholt** [comment]
@cloud-sid and @prabha-git, thanks for letting us know. I've opened #328 to add more details to the notebook about early access requirements for grounding w/ web search. And I'll update the notebook with any specific links/instructions as they become available.

And a friendly reminder that everyone involved in our projects should follow the [Contributor Code of Conduct](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/CODE_OF_CONDUCT.md) so that we can keep our community spaces as welcoming, friendly, and human as possible when working with each other and building awesome things with generative AI.
