### ISSUE TITLE
Quota exceeded for quota metric 'Generate Content API requests per minute'

### ISSUE THREAD

**Issue by kpripper** [GoogleCloudPlatform/generative-ai#382]
```
Quota exceeded for quota metric 'Generate Content API requests per minute' and limit 'GenerateContent request limit per minute for a region' of service 'generativelanguage.googleapis.com'
```

I've been seeing this message for OVER A DAY now. Why is there a limit of requests per MINUTE?

**Comment by holtskinner** [comment]
Hello, this issue is related to the [Google Gemini API](https://ai.google.dev/api/rest) not [Google Cloud Vertex AI](https://cloud.google.com/vertex-ai).

I'm unable to transfer the issue to the correct repository, so you will need to file a new issue in https://github.com/google/generative-ai-python/issues/new?assignees=&labels=type%3Abug%2Ccomponent%3Apython+sdk&projects=&template=bug_report.yml
