### ISSUE TITLE
[Bug]: Grounding with Gemini doesn't work, no metadata is returned

### ISSUE THREAD

**Issue by sanjanalreddy** [GoogleCloudPlatform/generative-ai#688]
### File Name

https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/grounding/intro-grounding-gemini.ipynb

### What happened?

Grounding with Gemini doesn't work. Gemini model doesn't seem to be using the grounding source to answer the prompt. The same datasource with Palm however returns grounded responses and grounding metadata. 

<img width="475" alt="Screenshot 2024-05-09 at 4 27 36 PM" src="https://github.com/GoogleCloudPlatform/generative-ai/assets/10604151/e205b516-4d00-4eaf-88ab-118cbd944add">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by holtskinner** [comment]
Can you provide details about the specific queries and data source you're using for grounding?

**Comment by sanjanalreddy** [comment]
I'm using the same data source that is mentioned in the notebook that points to `cloud.google.com/*` and the prompt is `When should I use an object table in BigQuery? And how does it store data?`

**Comment by maralm** [comment]
Similar experience here. The `grounding_metadata` contains the `retrieval_queries` property only, but nothing that looks like citations or attributions. For example, the method `print_grounding_response` in [the grounding example](https://github.com/GoogleCloudPlatform/generative-ai/blob/main/gemini/grounding/intro-grounding-gemini.ipynb#Helper-functions) indicates that there should be attributions available, but I'm consistently not getting any.

- SDK: google-cloud-aiplatform-1.53.0
- Data sources: both custom data set as well as an indexed web site in Vertex AI Search and Conversation
- Queries: Simple one-shot prompts

I'm a bit perplexed in general because I can set up a prompt and grounding source in the Vertex AI UI, try it out and it works okay, then click "Get Code" and execute that code and get no results. In general, results seem to be much worse using latest SDK and Gemini models, compared to the previous way of doing it and with text-bison.
